### ISSUE TITLE
tx-submission decision logic for the inbound side

### ISSUE THREAD

**Issue by coot** [IntersectMBO/ouroboros-network#3311]
To smooth traffic and save bandwidth, we can add a decision logic to inbound
tx-submission protocol which would decide from whom to download an available
transaction and trace which transactions are being downloaded (so we don't
start to download something that's already being downloaded).

## todo list

* [x] validate `tx` size
* [x] validate that `tx` size is smaller than maximum tx size
* [ ] efficient adding `txs` to mempool (do not try add the same `tx` twice)
      Is this even needed? Mempool could check `txid`s before doing any expensive validation.

**Comment by dcoutts** [comment]
This would be a design change with the following benefits:
1. substantially reduced bandwidth for tx broadcast
2. smoothing out refilling of the mempool to reduce bursty CPU and network use

This will be a useful optimisation as we get towards higher and higher chain throughput / TPS. For the moment (at current low TPS rates) it is not a significant issue. The effects are only visible in benchmarks with very high TPS.

**Comment by coot** [comment]
@lehins, we were thinking about something even simpler, checking if a given `txid` is in the mempool already before doing any ledger validation. IntersectMBO/cardano-ledger#4967 is even better.
