### ISSUE TITLE
Bootstrap Peers

### ISSUE THREAD

**Issue by bolt12** [IntersectMBO/ouroboros-network#4615]
## Boostrap Peers

Bootstrap peers are designed to provide safety guarantee for nodes joining the network while still taking advantage of the distributed network for nodes that are synced.  This will be an intermediate step before Genesis which will allow to further distribute the system.  The bootstrap peers will be run by some trusted parners like CF, Emurgo or IOG.   They are primarly designed for leaf nodes (e.g. full node wallets), who often end up syncing and require access to honest chain.

Here's some relevant links regarding this issue:

- https://github.com/input-output-hk/ouroboros-consensus/issues/101
- https://github.com/input-output-hk/ouroboros-consensus/pull/200

## Implementation plan

* [ ] #4555 API from the consensus which provides information if we are in caught up or syncing mode
* [x] Add new boostrap peer notion to Governor state
  * [x] mechanism to obtain bootstrap peers from an URL over https
* [x] changes to the outbound governor to accommodate transition changes between caught-up and syncing states
* [ ] adaptation of `PeerStateActions` - they need to be aware of the transition, so the source of peers is changed
* [ ] extend tests to cover bootstrap peers, especially the transition between both states. And making sure the [IER](https://github.com/input-output-hk/ouroboros-consensus/pull/200) is respected

In practice, the topology file will remain largely the same, however we will need a new field which provides bootstrap peers URL. Bootstrap peers will serve to sync the node until it is near the tip, and will also act as a fallback set when the node falls significantly behind the tip. This depends on #4555 .

### Notes

Edge nodes (daedalus wallets) are not expected to use local roots.  We are planing to preserve local roots even when bootstrap peers are being used in syncing mode.  Local roots are considered trusted nodes.

After having the notion of bootstrapping peers one needs to make sure that whenever the node gets far behind the tip we switch to only using bootstrapping peers instead of peers from the ledger. I think a good way to have this is to make the outbound governor aware of the state of the tip (i.e. if we are behind or close) and use that in the peer picking policy so as to only pick bootstrapping peers.

## References

Related to #3969.
