### ISSUE TITLE
New Typed-Protocols API

### ISSUE THREAD

**Issue by coot** [IntersectMBO/ouroboros-network#4936]
This issues tracks progress of merging all the PRs related to input-output-hk/typed-protocols#52:

* [x] input-output-hk/typed-protocols#52
* [x] input-output-hk/typed-protocols#61
* [x] IntersectMBO/ouroboros-network#4935
* [x] IntersectMBO/ouroboros-consensus#1223
* [ ] IntersectMBO/cardano-api#619
* [ ] IntersectMBO/cardano-cli#870
* [x] input-output-hk/ekg-forward#35
* [ ] IntersectMBO/cardano-node#5956
